; Script generated by Antigravity AI for Contracts App Professional

[Setup]
AppId={{D3E5D7B2-C7D1-4E8F-A6B1-3E2A5D7C9F01}
AppName=Сервиз
AppVersion=1.1.5
AppPublisher=VladPos Systems
DefaultDirName={autopf}\ContractsAppPro
DefaultGroupName=Contracts App Pro
AllowNoIcons=yes
OutputDir=installer
OutputBaseFilename=ContractsApp_Setup
SetupIconFile=resources\vladpos_logo.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "bulgarian"; MessagesFile: "compiler:Languages\Bulgarian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\ContractsApp_v1\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Contracts App Professional"; Filename: "{app}\ContractsApp_v1.exe"
Name: "{group}\{cm:UninstallProgram,Contracts App Professional}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\Contracts App Professional"; Filename: "{app}\ContractsApp_v1.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\ContractsApp_v1.exe"; Description: "{cm:LaunchProgram,Contracts App Professional}"; Flags: nowait postinstall skipifsilent
